[package]
name = "dawproject"
version = "0.4.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hifa-lang/dawproject.git"
documentation = "https://docs.rs/dawproject/latest/dawproject/"
description = "A port of DAWproject in Rust."
readme = "README.md"
edition = "2021"

[dependencies]
thiserror = "1.0.58"
xml-schema = "0.3.0"
xml-schema-derive = "0.3.0"
yaserde = "0.10.0"
yaserde_derive = "0.10.0"
zip = "0.6"
